# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  app.form.registration:
    class: Klass\Bundle\UserBundle\Form\Type\RegistrationFormType
    tags:
      - { name: form.type, alias: klass_user_registration }
